name: DevSecOps Pipeline

on:
  push:
    branches: [ main ]


jobs:
  security:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    # -------------------------
    # OWASP Dependency Check (SCA)
    # -------------------------
    - name: Dependency Check
      uses: dependency-check/Dependency-Check_Action@main
      with:
        project: "PAI4"
        path: "."
        format: "XML"
        out: "dependency-check-report"

    - name: Upload Dependency report to DefectDojo
      env:
        DD_URL: ${{ secrets.DD_URL }}
        DD_API_KEY: ${{ secrets.DD_API_KEY }}
        DD_ENGAGEMENT_ID: ${{ vars.DD_ENGAGEMENT_ID }}
      run: |
        curl -X POST "$DD_URL/api/v2/import-scan/" \
          -H "Authorization: Token $DD_API_KEY" \
          -F "scan_type=Dependency Check Scan" \
          -F "file=@reports/dependency-check-report.xml" \
          -F "engagement=$DD_ENGAGEMENT_ID"

    # -------------------------
    # Bearer (SAST)
    # -------------------------
    - name: Run Bearer
      uses: bearer/bearer-action@v2
      with:
        format: json
        output: bearer-report.json

    - name: Upload Bearer report to DefectDojo
      env:
        DD_URL: ${{ secrets.DD_URL }}
        DD_API_KEY: ${{ secrets.DD_API_KEY }}
        DD_ENGAGEMENT_ID: ${{ vars.DD_ENGAGEMENT_ID }}
      run: |
        curl -X POST "$DD_URL/api/v2/import-scan/" \
          -H "Authorization: Token $DD_API_KEY" \
          -F "scan_type=Generic Findings Import" \
          -F "file=@bearer-report.json" \
          -F "engagement=$DD_ENGAGEMENT_ID"

    # -------------------------
    # SemGrep (IAST)
    # -------------------------
    - name: Run Semgrep
      uses: returntocorp/semgrep-action@v1
      with:
        config: auto
        output: semgrep-report.json

    - name: Upload Semgrep reports to DefectDojo
      env:
        DD_URL: ${{ secrets.DD_URL }}
        DD_API_KEY: ${{ secrets.DD_API_KEY }}
        DD_ENGAGEMENT_ID: ${{ vars.DD_ENGAGEMENT_ID }}
      run: |
        curl -X POST "$DD_URL/api/v2/import-scan/" \
          -H "Authorization: Token $DD_API_KEY" \
          -F "scan_type=Semgrep JSON Report" \
          -F "file=@semgrep-report.json" \
          -F "engagement=$DD_ENGAGEMENT_ID"

