name: DevSecOps Pipeline

on:
  push:
    branches: [ main ]


jobs:
  security:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    # -------------------------
    # OWASP Dependency Check (SCA)
    # -------------------------
    - name: Dependency Check
      uses: dependency-check/Dependency-Check_Action@main
      if: always()
      with:
        project: "PAI4"
        path: "."
        format: "XML"
        out: "dependency-check-report"

    - name: Upload Dependency report to DefectDojo
      if: always()
      env:
        DD_URL: ${{ secrets.DD_URL }}
        DD_API_KEY: ${{ secrets.DD_API_KEY }}
        DD_ENGAGEMENT_ID: ${{ vars.DD_ENGAGEMENT_ID }}
      run: |
        curl -X POST "$DD_URL/api/v2/import-scan/" \
          -H "Authorization: Token $DD_API_KEY" \
          -F "scan_type=Dependency Check Scan" \
          -F "file=@dependency-check-report/dependency-check-report.xml" \
          -F "engagement=$DD_ENGAGEMENT_ID"

    # -------------------------
    # Bearer (SAST)
    # -------------------------
    - name: Run Bearer
      uses: bearer/bearer-action@v2
      if: always()
      with:
        format: json
        output: bearer-report.json

    - name: Upload Bearer report to DefectDojo
      if: always()
      env:
        DD_URL: ${{ secrets.DD_URL }}
        DD_API_KEY: ${{ secrets.DD_API_KEY }}
        DD_ENGAGEMENT_ID: ${{ vars.DD_ENGAGEMENT_ID }}
      run: |
        curl -X POST "$DD_URL/api/v2/import-scan/" \
          -H "Authorization: Token $DD_API_KEY" \
          -F "scan_type=Generic Findings Import" \
          -F "file=@bearer-report.json" \
          -F "engagement=$DD_ENGAGEMENT_ID"

    # -------------------------
    # Start application (required for ZAP)
    # -------------------------
    - name: Start app
      run: |
        npm start &
        sleep 2

    # -------------------------
    # OWASP ZAP (DAST)
    # -------------------------
    - name: Run OWASP ZAP Baseline Scan
      uses: zaproxy/action-baseline@v0.10.0
      if: always()
      with:
        target: 'http://localhost:3000'
        format: 'xml'
        cmd_options: '-a -x report_xml.xml'

    - name: Upload ZAP report to DefectDojo
      if: always()
      env:
        DD_URL: ${{ secrets.DD_URL }}
        DD_API_KEY: ${{ secrets.DD_API_KEY }}
        DD_ENGAGEMENT_ID: ${{ vars.DD_ENGAGEMENT_ID }}
      run: |
        curl -X POST "$DD_URL/api/v2/import-scan/" \
          -H "Authorization: Token $DD_API_KEY" \
          -F "scan_type=ZAP Scan" \
          -F "file=@report_xml.xml" \
          -F "engagement=$DD_ENGAGEMENT_ID"

    - name: (DEBUG) List file structure
      if: always()
      run: ls -R --ignore=node_modules
